#!/bin/bash
PATH_FORKS="/usr/share/chia"
PATH_HOME="/home/toor"
FARMER_HOST="192.168.0.222"

sh exec.sh "$PATH_FORKS/aedge-blockchain" "aedge" "$PATH_HOME/.aedge" "$FARMER_HOST:8959"
sh exec.sh "$PATH_FORKS/apple-blockchain" "apple" "$PATH_HOME/.apple" "$FARMER_HOST:26667"
sh exec.sh "$PATH_FORKS/avocado-blockchain" "avocado" "$PATH_HOME/.avocado" "$FARMER_HOST:6868"
sh exec.sh "$PATH_FORKS/bpx-blockchain" "bpx" "$PATH_HOME/.bpx" "$FARMER_HOST:27914"
sh exec.sh "$PATH_FORKS/btcgreen-blockchain" "btcgreen" "$PATH_HOME/.btcgreen" "$FARMER_HOST:18655"
sh exec.sh "$PATH_FORKS/cactus-blockchain" "cactus" "$PATH_HOME/.cactus" "$FARMER_HOST:11447"
sh exec.sh "$PATH_FORKS/cannabis-blockchain" "cannabis" "$PATH_HOME/.cannabis" "$FARMER_HOST:5547"
sh exec.sh "$PATH_FORKS/chia-blockchain" "chia" "$PATH_HOME/.chia" "$FARMER_HOST:8447"
sh exec.sh "$PATH_FORKS/doge-chia" "dogechia" "$PATH_HOME/.dogechia" "$FARMER_HOST:6969"
sh exec.sh "$PATH_FORKS/ext9-blockchain" "chia" "$PATH_HOME/.chia/ext9" "$FARMER_HOST:38447"
sh exec.sh "$PATH_FORKS/flax-blockchain" "flax" "$PATH_HOME/.flax" "$FARMER_HOST:6885"
sh exec.sh "$PATH_FORKS/flora-blockchain" "flora" "$PATH_HOME/.flora" "$FARMER_HOST:18647"
sh exec.sh "$PATH_FORKS/gold-blockchain" "gold" "$PATH_HOME/.gold" "$FARMER_HOST:14447"
sh exec.sh "$PATH_FORKS/greendoge-blockchain" "greendoge" "$PATH_HOME/.greendoge" "$FARMER_HOST:6547"
sh exec.sh "$PATH_FORKS/hddcoin-blockchain" "hddcoin" "$PATH_HOME/.hddcoin" "$FARMER_HOST:28447"
sh exec.sh "$PATH_FORKS/kale-blockchain" "kale" "$PATH_HOME/.kale" "$FARMER_HOST:6335"
sh exec.sh "$PATH_FORKS/maize-blockchain" "maize" "$PATH_HOME/.maize" "$FARMER_HOST:8647"
sh exec.sh "$PATH_FORKS/mint-blockchain" "mint" "$PATH_HOME/.mint" "$FARMER_HOST:29227"
sh exec.sh "$PATH_FORKS/petroleum-blockchain" "petroleum" "$PATH_HOME/.petroleum" "$FARMER_HOST:33347"
sh exec.sh "$PATH_FORKS/seno-blockchain" "seno" "$PATH_HOME/.seno2" "$FARMER_HOST:18447"
sh exec.sh "$PATH_FORKS/silicoin-blockchain" "sit" "$PATH_HOME/.sit" "$FARMER_HOST:22447"
sh exec.sh "$PATH_FORKS/spare-blockchain" "spare" "$PATH_HOME/.spare-blockchain" "$FARMER_HOST:9447"
sh exec.sh "$PATH_FORKS/staicoin-blockchain" "stai" "$PATH_HOME/.stai" "$FARMER_HOST:1692"
sh exec.sh "$PATH_FORKS/stor-blockchain" "stor" "$PATH_HOME/.stor" "$FARMER_HOST:8338"
sh exec.sh "$PATH_FORKS/taco-blockchain" "taco" "$PATH_HOME/.taco" "$FARMER_HOST:18623"
sh exec.sh "$PATH_FORKS/tad-blockchain" "tad" "$PATH_HOME/.tad" "$FARMER_HOST:4447"
sh exec.sh "$PATH_FORKS/tranzact-blockchain" "tranzact" "$PATH_HOME/.tranzact" "$FARMER_HOST:8652"
sh exec.sh "$PATH_FORKS/venidium-blockchain" "venidium" "$PATH_HOME/.venidium" "$FARMER_HOST:5747"
sh exec.sh "$PATH_FORKS/wheat-blockchain" "wheat" "$PATH_HOME/.wheat" "$FARMER_HOST:21447"