#!/bin/bash
PATH_FORKS="/usr/share/chia"
PATH_HOME="/home/toor"
FARMER_HOST="192.168.0.222"
sh exec.sh "$PATH_FORKS/apple-blockchain" "apple" "$PATH_HOME/.apple" "$FARMER_HOST:26667"
sh exec.sh "$PATH_FORKS/avocado-blockchain" "avocado" "$PATH_HOME/.avocado" "$FARMER_HOST:6868"
sh exec.sh "$PATH_FORKS/cactus-blockchain" "cactus" "$PATH_HOME/.cactus" "$FARMER_HOST:11447"
sh exec.sh "$PATH_FORKS/cannabis-blockchain" "cannabis" "$PATH_HOME/.cannabis" "$FARMER_HOST:5547"
sh exec.sh "$PATH_FORKS/chaingreen-blockchain" "chaingreen" "$PATH_HOME/.chaingreen" "$FARMER_HOST:8777"
sh exec.sh "$PATH_FORKS/chiadogecoin" "chiadoge" "$PATH_HOME/.chiadoge" "$FARMER_HOST:6895"
sh exec.sh "$PATH_FORKS/chia-rosechain" "chia" "$PATH_HOME/.chiarose" "$FARMER_HOST:8547"
sh exec.sh "$PATH_FORKS/covid-blockchain" "covid" "$PATH_HOME/.covid" "$FARMER_HOST:18129"
sh exec.sh "$PATH_FORKS/doge-chia" "dogechia" "$PATH_HOME/.dogechia" "$FARMER_HOST:6969"
sh exec.sh "$PATH_FORKS/equality-blockchain" "equality" "$PATH_HOME/.equality" "$FARMER_HOST:9885"
sh exec.sh "$PATH_FORKS/flax-blockchain" "flax" "$PATH_HOME/.flax" "$FARMER_HOST:6885"
sh exec.sh "$PATH_FORKS/flora-blockchain" "flora" "$PATH_HOME/.flora" "$FARMER_HOST:18647"
sh exec.sh "$PATH_FORKS/fork-blockchain" "fork" "$PATH_HOME/.fork" "$FARMER_HOST:16625"
sh exec.sh "$PATH_FORKS/goji-blockchain" "goji" "$PATH_HOME/.goji-blockchain" "$FARMER_HOST:7447"
sh exec.sh "$PATH_FORKS/greendoge-blockchain" "greendoge" "$PATH_HOME/.greendoge" "$FARMER_HOST:6547"
sh exec.sh "$PATH_FORKS/hddcoin-blockchain" "hddcoin" "$PATH_HOME/.hddcoin" "$FARMER_HOST:28447"
sh exec.sh "$PATH_FORKS/kale-blockchain" "kale" "$PATH_HOME/.kale" "$FARMER_HOST:6335"
sh exec.sh "$PATH_FORKS/maize-blockchain" "maize" "$PATH_HOME/.maize" "$FARMER_HOST:8647"
sh exec.sh "$PATH_FORKS/melati-blockchain" "melati" "$PATH_HOME/.melati" "$FARMER_HOST:2447"
sh exec.sh "$PATH_FORKS/sector-blockchain" "sector" "$PATH_HOME/.sector" "$FARMER_HOST:5447"
sh exec.sh "$PATH_FORKS/seno-blockchain" "seno" "$PATH_HOME/.seno2" "$FARMER_HOST:18447"
sh exec.sh "$PATH_FORKS/shamrock-blockchain" "shamrock" "$PATH_HOME/.shamrock" "$FARMER_HOST:9337"
sh exec.sh "$PATH_FORKS/silicoin-blockchain" "silicoin" "$PATH_HOME/.silicoin" "$FARMER_HOST:10447"
sh exec.sh "$PATH_FORKS/socks-blockchain" "socks" "$PATH_HOME/.socks" "$FARMER_HOST:58447"
sh exec.sh "$PATH_FORKS/spare-blockchain" "spare" "$PATH_HOME/.spare-blockchain" "$FARMER_HOST:9447"
sh exec.sh "$PATH_FORKS/taco-blockchain" "taco" "$PATH_HOME/.taco" "$FARMER_HOST:18623"
sh exec.sh "$PATH_FORKS/tad-blockchain" "tad" "$PATH_HOME/.tad" "$FARMER_HOST:4447"
sh exec.sh "$PATH_FORKS/wheat-blockchain" "wheat" "$PATH_HOME/.wheat" "$FARMER_HOST:21447