#!/bin/bash
sh install_apple.sh
sh install_avocado.sh
sh install_cactus.sh
sh install_cannabis.sh
sh install_chaingreen.sh
sh install_chia.sh
sh install_covid.sh
sh install_dogechia.sh
sh install_equality.sh
sh install_flax.sh
sh install_flora.sh
sh install_fork.sh
sh install_goji.sh
sh install_greendoge.sh
sh install_hddcoin.sh
sh install_kale.sh
sh install_maize.sh
sh install_melati.sh
sh install_rose.sh
sh install_sector.sh
sh install_seno.sh
sh install_silicoin.sh
sh install_socks.sh
sh install_spare.sh
sh install_taco.sh
sh install_tad.sh
sh install_wheat.sh

sh install_scam.sh
sh install_nchain.sh
#sh install_lucky.sh
