#!/bin/bash
systemctl stop apple.service
systemctl stop avocado.service
systemctl stop cactus.service
systemctl stop cannabis.service
systemctl stop chaingreen.service
#systemctl stop chia.service
systemctl stop covid.service
systemctl stop dogechia.service
#systemctl stop equality.service
systemctl stop flax.service
systemctl stop flora.service
systemctl stop fork.service
systemctl stop goji.service
systemctl stop greendoge.service
systemctl stop hddcoin.service
systemctl stop kale.service
systemctl stop maize.service
systemctl stop melati.service
systemctl stop rose.service
systemctl stop sector.service
systemctl stop seno.service
systemctl stop silicoin.service
systemctl stop socks.service
systemctl stop spare.service
systemctl stop taco.service
systemctl stop tad.service
systemctl stop wheat.service
systemctl stop scam.service
systemctl stop nchain.service
systemctl stop lucky.service
systemctl stop tranzact.service
systemctl stop btcgreen.service
systemctl stop mint.service
systemctl stop mogua.service
systemctl stop staicoin.service
systemctl stop aedge.service
systemctl stop stor.service
